language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      env:
        - COMPILER=g++-4.8
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: [g++-4.8, lcov]

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgtest-dev cmake
  - sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
  - sudo tar xf release-1.7.0.tar.gz
  - cd googletest-release-1.7.0
  - sudo cmake -DBUILD_SHARED_LIBS=ON .
  - sudo make
  - sudo cp -a include/gtest /usr/include
  - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
  - cd "${TRAVIS_BUILD_DIR}"
  - ls -l

before_script:
  - cd test/
  - cmake -Dtest=ON ../
  - make
  - ls -l
  - cd ..

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
  - cmake --build .
  - ctest .. --output-on-failure

after_success:
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -t fd59c9b2-732f-4edd-bea6-893ff5418ecf

branches:
  only:
    - ci
    - master
    - dev

notifications:
  email:
    - ilev4ik@gmail.com