language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      env:
        - COMPILER=g++-4.8
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: [g++-4.8]

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgtest-dev
  - sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
  - sudo tar xf release-1.7.0.tar.gz
  - cd googletest-release-1.7.0
  - sudo cmake -DBUILD_SHARED_LIBS=ON .
  - sudo make
  - sudo cp -a include/gtest /usr/include
  - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
  - cd "${TRAVIS_BUILD_DIR}"

before_script:
  - cd test/
  - cmake -Dtest=ON ../
  - make
  - ls -l

#script: "./easyloggingpp-unit-tests -v && cd ../samples/STL && pwd && sh ./.travis_build.sh && valgrind ./bin/very-basic.cpp.bin"
branches:
  only:
    - ci
    - master
    - dev