language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      env:
        - COMPILER=g++-4.8
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-tests']
          packages: [g++-4.8, lcov]

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgtest-dev cmake

install:
  - cd ${TRAVIS_BUILD_DIR}
  # gtest
  - sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
  - sudo tar xf release-1.7.0.tar.gz
  - cd googletest-release-1.7.0
  - sudo cmake -DBUILD_SHARED_LIBS=ON .
  - sudo make
  - sudo cp -a include/gtest /usr/include
  - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
  # lcov
  - sudo wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - sudo tar xf lcov_1.11.orig.tar.gz
  - sudo make -C lcov-1.11/ install
  - gem install coveralls-lcov
  - lcov --version
  - g++ --version
  - pwd && ls -la

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - cd tests/
  - cmake -Dtest=ON ../
  - make
  - pwd && ls -la

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  # configure cmake
  - cmake -DCMAKE_BUILD_TYPE="$BUILD_CONFIGURATION" -DTARGET_CPU="$TARGET_CPU" -DCODE_COVERAGE=ON ..
  # build program
  - cmake --build .
  # run tests
  - ctest --verbose --output-on-failure ..
  - pwd && ls -la

after_success:
  - lcov --directory . --capture --coverage.info
  - echo ${HOME}
  - lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"

branches:
  only:
    - ci
    - master
    - dev

notifications:
  email:
    - ilev4ik@gmail.com